//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BAISERA.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("B2BAISERA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B2BAITAG.
        /// </summary>
        internal static string ClientTag {
            get {
                return ResourceManager.GetString("ClientTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVXDFMyh18Tq9q1c8cr8hVsWKAe2/XC4L1+IkzzvUnuliArBgT4ROjwJGcTC4MV7Sh7fF99gvYO6Y+PFbRoNefQJmlXZZNRMs1+a1FZ2bkCLa/2juaykBlKqReQawfBA2DD1jPCggILaxMVRKCukXa4G93jbMCL+SMYqQpM9HrE=.
        /// </summary>
        internal static string EncryptPassword {
            get {
                return ResourceManager.GetString("EncryptPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVXDFMyh18Tq9q1c8cr8hVsWKAe2/XC4L1+IkzzvUnuliArBgT4ROjwJGcTC4MV7Sh7fF99gvYO6Y+PFbRoNefQJmlXZZNRMs1+a1FZ2bkCLa/2juaykBlKqReQawfBA2DD1jPCggILaxMVRKCukXa4G93jbMCL+SMYqQpM9HrE=.
        /// </summary>
        internal static string EncryptUserName {
            get {
                return ResourceManager.GetString("EncryptUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to serasera.
        /// </summary>
        internal static string NetworkCredentialPassword {
            get {
                return ResourceManager.GetString("NetworkCredentialPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trac.astra.co.id.
        /// </summary>
        internal static string NetworkCredentialProxy {
            get {
                return ResourceManager.GetString("NetworkCredentialProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to genrpt.
        /// </summary>
        internal static string NetworkCredentialUserName {
            get {
                return ResourceManager.GetString("NetworkCredentialUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SERA.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.10.8.189.
        /// </summary>
        internal static string WebProxyAddress {
            get {
                return ResourceManager.GetString("WebProxyAddress", resourceCulture);
            }
        }
    }
}
