//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BAISERA.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apps.astra.co.id/B2BAIWebServiceDMZ/B2BAIWebServiceDMZ.asmx")]
        public string B2BAISERA_S02001_WsProd_B2BAIWebServiceDMZ {
            get {
                return ((string)(this["B2BAISERA_S02001_WsProd_B2BAIWebServiceDMZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apps.astra.co.id/B2BAIWebServiceDMZ/B2BAIWebServiceDMZ.asmx")]
        public string B2BAISERA_S02001_WsDev_B2BAIWebServiceDMZ {
            get {
                return ((string)(this["B2BAISERA_S02001_WsDev_B2BAIWebServiceDMZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apps.astra.co.id/B2BAIWebServiceDMZ/B2BAIWebServiceDMZ.asmx")]
        public string B2BAISERA_WebReferenceB2BAISERA_B2BAIWebServiceDMZ {
            get {
                return ((string)(this["B2BAISERA_WebReferenceB2BAISERA_B2BAIWebServiceDMZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apps.astra.co.id/B2BAIWebServiceDMZ/B2BAIWebServiceDMZ.asmx")]
        public string B2BAISERA_WsReferenceB2BAISERA_WsB2BAISERA {
            get {
                return ((string)(this["B2BAISERA_WsReferenceB2BAISERA_WsB2BAISERA"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apps.astra.co.id/B2BAIWebServiceDMZ/B2BAIWebServiceDMZ.asmx")]
        public string B2BAISERA_S02009_WsProd_B2BAIWebServiceDMZ {
            get {
                return ((string)(this["B2BAISERA_S02009_WsProd_B2BAIWebServiceDMZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apps.astra.co.id/B2BAIWebServiceDMZ/B2BAIWebServiceDMZ.asmx")]
        public string B2BAISERA_S02009_WsDev_B2BAIWebServiceDMZ {
            get {
                return ((string)(this["B2BAISERA_S02009_WsDev_B2BAIWebServiceDMZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apps.astra.co.id/B2BAIWebServiceDMZ/B2BAIWebServiceDMZ.asmx")]
        public string B2BAISERA_S02001_WsDevUTT_B2BAIWebServiceDMZ {
            get {
                return ((string)(this["B2BAISERA_S02001_WsDevUTT_B2BAIWebServiceDMZ"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apps.astra.co.id/B2BAIWebServiceDMZ/B2BAIWebServiceDMZ.asmx")]
        public string B2BAISERA_S02009_WsDevUTT_B2BAIWebServiceDMZ {
            get {
                return ((string)(this["B2BAISERA_S02009_WsDevUTT_B2BAIWebServiceDMZ"]));
            }
        }
    }
}
