//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.1.
// 
#pragma warning disable 1591

namespace B2BAISERA.WsReferenceB2BAISERA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsB2BAISERASoap", Namespace="http://apps.astra.co.id/")]
    public partial class WsB2BAISERA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginAuthenticationOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateDocumentStatusOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsB2BAISERA() {
            this.Url = global::B2BAISERA.Properties.Settings.Default.B2BAISERA_WsReferenceB2BAISERA_WsB2BAISERA;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event LoginAuthenticationCompletedEventHandler LoginAuthenticationCompleted;
        
        /// <remarks/>
        public event UploadDocumentCompletedEventHandler UploadDocumentCompleted;
        
        /// <remarks/>
        public event DownloadDocumentCompletedEventHandler DownloadDocumentCompleted;
        
        /// <remarks/>
        public event UpdateDocumentStatusCompletedEventHandler UpdateDocumentStatusCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.astra.co.id/HelloWorld", RequestNamespace="http://apps.astra.co.id/", ResponseNamespace="http://apps.astra.co.id/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.astra.co.id/LoginAuthentication", RequestNamespace="http://apps.astra.co.id/", ResponseNamespace="http://apps.astra.co.id/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LoginAuthenticationViewModel LoginAuthentication(loginRequest loginRequest) {
            object[] results = this.Invoke("LoginAuthentication", new object[] {
                        loginRequest});
            return ((LoginAuthenticationViewModel)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAuthenticationAsync(loginRequest loginRequest) {
            this.LoginAuthenticationAsync(loginRequest, null);
        }
        
        /// <remarks/>
        public void LoginAuthenticationAsync(loginRequest loginRequest, object userState) {
            if ((this.LoginAuthenticationOperationCompleted == null)) {
                this.LoginAuthenticationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginAuthenticationOperationCompleted);
            }
            this.InvokeAsync("LoginAuthentication", new object[] {
                        loginRequest}, this.LoginAuthenticationOperationCompleted, userState);
        }
        
        private void OnLoginAuthenticationOperationCompleted(object arg) {
            if ((this.LoginAuthenticationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginAuthenticationCompleted(this, new LoginAuthenticationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.astra.co.id/UploadDocument", RequestNamespace="http://apps.astra.co.id/", ResponseNamespace="http://apps.astra.co.id/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UploadDocumentViewModel UploadDocument(uploadRequest uploadRequest) {
            object[] results = this.Invoke("UploadDocument", new object[] {
                        uploadRequest});
            return ((UploadDocumentViewModel)(results[0]));
        }
        
        /// <remarks/>
        public void UploadDocumentAsync(uploadRequest uploadRequest) {
            this.UploadDocumentAsync(uploadRequest, null);
        }
        
        /// <remarks/>
        public void UploadDocumentAsync(uploadRequest uploadRequest, object userState) {
            if ((this.UploadDocumentOperationCompleted == null)) {
                this.UploadDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadDocumentOperationCompleted);
            }
            this.InvokeAsync("UploadDocument", new object[] {
                        uploadRequest}, this.UploadDocumentOperationCompleted, userState);
        }
        
        private void OnUploadDocumentOperationCompleted(object arg) {
            if ((this.UploadDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadDocumentCompleted(this, new UploadDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.astra.co.id/DownloadDocument", RequestNamespace="http://apps.astra.co.id/", ResponseNamespace="http://apps.astra.co.id/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DownloadDocumentViewModel DownloadDocument(downloadRequest downloadRequest) {
            object[] results = this.Invoke("DownloadDocument", new object[] {
                        downloadRequest});
            return ((DownloadDocumentViewModel)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadDocumentAsync(downloadRequest downloadRequest) {
            this.DownloadDocumentAsync(downloadRequest, null);
        }
        
        /// <remarks/>
        public void DownloadDocumentAsync(downloadRequest downloadRequest, object userState) {
            if ((this.DownloadDocumentOperationCompleted == null)) {
                this.DownloadDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadDocumentOperationCompleted);
            }
            this.InvokeAsync("DownloadDocument", new object[] {
                        downloadRequest}, this.DownloadDocumentOperationCompleted, userState);
        }
        
        private void OnDownloadDocumentOperationCompleted(object arg) {
            if ((this.DownloadDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadDocumentCompleted(this, new DownloadDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://apps.astra.co.id/UpdateDocumentStatus", RequestNamespace="http://apps.astra.co.id/", ResponseNamespace="http://apps.astra.co.id/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UpdateDocumentViewModel UpdateDocumentStatus(updateStatusRequest updateStatusRequest) {
            object[] results = this.Invoke("UpdateDocumentStatus", new object[] {
                        updateStatusRequest});
            return ((UpdateDocumentViewModel)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateDocumentStatusAsync(updateStatusRequest updateStatusRequest) {
            this.UpdateDocumentStatusAsync(updateStatusRequest, null);
        }
        
        /// <remarks/>
        public void UpdateDocumentStatusAsync(updateStatusRequest updateStatusRequest, object userState) {
            if ((this.UpdateDocumentStatusOperationCompleted == null)) {
                this.UpdateDocumentStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateDocumentStatusOperationCompleted);
            }
            this.InvokeAsync("UpdateDocumentStatus", new object[] {
                        updateStatusRequest}, this.UpdateDocumentStatusOperationCompleted, userState);
        }
        
        private void OnUpdateDocumentStatusOperationCompleted(object arg) {
            if ((this.UpdateDocumentStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateDocumentStatusCompleted(this, new UpdateDocumentStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class loginRequest {
        
        private string userNameField;
        
        private string passwordField;
        
        private string clientTagField;
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string ClientTag {
            get {
                return this.clientTagField;
            }
            set {
                this.clientTagField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class UpdateDocumentViewModel {
        
        private bool acknowledgeField;
        
        private string ticketNoField;
        
        private string messageField;
        
        /// <remarks/>
        public bool Acknowledge {
            get {
                return this.acknowledgeField;
            }
            set {
                this.acknowledgeField = value;
            }
        }
        
        /// <remarks/>
        public string TicketNo {
            get {
                return this.ticketNoField;
            }
            set {
                this.ticketNoField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class TransactionDataID {
        
        private string transGUIDField;
        
        private string documentNumberField;
        
        private string key1Field;
        
        private string key2Field;
        
        private string key3Field;
        
        private string transStatusField;
        
        private string logMessageField;
        
        /// <remarks/>
        public string TransGUID {
            get {
                return this.transGUIDField;
            }
            set {
                this.transGUIDField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Key1 {
            get {
                return this.key1Field;
            }
            set {
                this.key1Field = value;
            }
        }
        
        /// <remarks/>
        public string Key2 {
            get {
                return this.key2Field;
            }
            set {
                this.key2Field = value;
            }
        }
        
        /// <remarks/>
        public string Key3 {
            get {
                return this.key3Field;
            }
            set {
                this.key3Field = value;
            }
        }
        
        /// <remarks/>
        public string TransStatus {
            get {
                return this.transStatusField;
            }
            set {
                this.transStatusField = value;
            }
        }
        
        /// <remarks/>
        public string LogMessage {
            get {
                return this.logMessageField;
            }
            set {
                this.logMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class updateStatusRequest {
        
        private string ticketNoField;
        
        private string clientTagField;
        
        private TransactionDataID[] transactionDataIDField;
        
        /// <remarks/>
        public string TicketNo {
            get {
                return this.ticketNoField;
            }
            set {
                this.ticketNoField = value;
            }
        }
        
        /// <remarks/>
        public string ClientTag {
            get {
                return this.clientTagField;
            }
            set {
                this.clientTagField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDataID[] transactionDataID {
            get {
                return this.transactionDataIDField;
            }
            set {
                this.transactionDataIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class DownloadDocumentViewModel {
        
        private bool acknowledgeField;
        
        private string ticketNoField;
        
        private string messageField;
        
        private TransactionDataModel[] transactionDataField;
        
        /// <remarks/>
        public bool Acknowledge {
            get {
                return this.acknowledgeField;
            }
            set {
                this.acknowledgeField = value;
            }
        }
        
        /// <remarks/>
        public string TicketNo {
            get {
                return this.ticketNoField;
            }
            set {
                this.ticketNoField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDataModel[] transactionData {
            get {
                return this.transactionDataField;
            }
            set {
                this.transactionDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class TransactionDataModel {
        
        private int idField;
        
        private int transactionIDField;
        
        private string transGUIDField;
        
        private string documentNumberField;
        
        private string fileTypeField;
        
        private string iPAddressField;
        
        private string destinationUserField;
        
        private string key1Field;
        
        private string key2Field;
        
        private string key3Field;
        
        private int dataLengthField;
        
        private string rowStatusField;
        
        private string[] dataField;
        
        /// <remarks/>
        public int ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
            }
        }
        
        /// <remarks/>
        public string TransGUID {
            get {
                return this.transGUIDField;
            }
            set {
                this.transGUIDField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        public string IPAddress {
            get {
                return this.iPAddressField;
            }
            set {
                this.iPAddressField = value;
            }
        }
        
        /// <remarks/>
        public string DestinationUser {
            get {
                return this.destinationUserField;
            }
            set {
                this.destinationUserField = value;
            }
        }
        
        /// <remarks/>
        public string Key1 {
            get {
                return this.key1Field;
            }
            set {
                this.key1Field = value;
            }
        }
        
        /// <remarks/>
        public string Key2 {
            get {
                return this.key2Field;
            }
            set {
                this.key2Field = value;
            }
        }
        
        /// <remarks/>
        public string Key3 {
            get {
                return this.key3Field;
            }
            set {
                this.key3Field = value;
            }
        }
        
        /// <remarks/>
        public int DataLength {
            get {
                return this.dataLengthField;
            }
            set {
                this.dataLengthField = value;
            }
        }
        
        /// <remarks/>
        public string RowStatus {
            get {
                return this.rowStatusField;
            }
            set {
                this.rowStatusField = value;
            }
        }
        
        /// <remarks/>
        public string[] Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class downloadRequest {
        
        private string ticketNoField;
        
        private string clientTagField;
        
        private string fileTypeField;
        
        private string sourceUserField;
        
        private string statusField;
        
        private System.DateTime transDateFromField;
        
        private System.DateTime transDateToField;
        
        private string key1Field;
        
        private string key2Field;
        
        private string key3Field;
        
        /// <remarks/>
        public string TicketNo {
            get {
                return this.ticketNoField;
            }
            set {
                this.ticketNoField = value;
            }
        }
        
        /// <remarks/>
        public string ClientTag {
            get {
                return this.clientTagField;
            }
            set {
                this.clientTagField = value;
            }
        }
        
        /// <remarks/>
        public string FileType {
            get {
                return this.fileTypeField;
            }
            set {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SourceUser {
            get {
                return this.sourceUserField;
            }
            set {
                this.sourceUserField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransDateFrom {
            get {
                return this.transDateFromField;
            }
            set {
                this.transDateFromField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TransDateTo {
            get {
                return this.transDateToField;
            }
            set {
                this.transDateToField = value;
            }
        }
        
        /// <remarks/>
        public string Key1 {
            get {
                return this.key1Field;
            }
            set {
                this.key1Field = value;
            }
        }
        
        /// <remarks/>
        public string Key2 {
            get {
                return this.key2Field;
            }
            set {
                this.key2Field = value;
            }
        }
        
        /// <remarks/>
        public string Key3 {
            get {
                return this.key3Field;
            }
            set {
                this.key3Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class UploadDocumentViewModel {
        
        private bool acknowledgeField;
        
        private string ticketNoField;
        
        private string messageField;
        
        /// <remarks/>
        public bool Acknowledge {
            get {
                return this.acknowledgeField;
            }
            set {
                this.acknowledgeField = value;
            }
        }
        
        /// <remarks/>
        public string TicketNo {
            get {
                return this.ticketNoField;
            }
            set {
                this.ticketNoField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class uploadRequest {
        
        private string ticketNoField;
        
        private string clientTagField;
        
        private TransactionDataModel[] transactionDataField;
        
        /// <remarks/>
        public string TicketNo {
            get {
                return this.ticketNoField;
            }
            set {
                this.ticketNoField = value;
            }
        }
        
        /// <remarks/>
        public string ClientTag {
            get {
                return this.clientTagField;
            }
            set {
                this.clientTagField = value;
            }
        }
        
        /// <remarks/>
        public TransactionDataModel[] transactionData {
            get {
                return this.transactionDataField;
            }
            set {
                this.transactionDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class LoginAuthenticationViewModel {
        
        private bool acknowledgeField;
        
        private string ticketNoField;
        
        private string messageField;
        
        /// <remarks/>
        public bool Acknowledge {
            get {
                return this.acknowledgeField;
            }
            set {
                this.acknowledgeField = value;
            }
        }
        
        /// <remarks/>
        public string TicketNo {
            get {
                return this.ticketNoField;
            }
            set {
                this.ticketNoField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LoginAuthenticationCompletedEventHandler(object sender, LoginAuthenticationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginAuthenticationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginAuthenticationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LoginAuthenticationViewModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LoginAuthenticationViewModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UploadDocumentCompletedEventHandler(object sender, UploadDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UploadDocumentViewModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UploadDocumentViewModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DownloadDocumentCompletedEventHandler(object sender, DownloadDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DownloadDocumentViewModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DownloadDocumentViewModel)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateDocumentStatusCompletedEventHandler(object sender, UpdateDocumentStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateDocumentStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateDocumentStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UpdateDocumentViewModel Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UpdateDocumentViewModel)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591