//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BSERAWebService.Model.DataAccess
{
    public partial class Response
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string WebServiceName
        {
            get;
            set;
        }
    
        public virtual string MethodName
        {
            get;
            set;
        }
    
        public virtual bool Acknowledge
        {
            get;
            set;
        }
    
        public virtual string TicketNo
        {
            get;
            set;
        }
    
        public virtual string Message
        {
            get;
            set;
        }
    
        public virtual string CreatedWho
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedWhen
        {
            get;
            set;
        }
    
        public virtual string ChangedWho
        {
            get;
            set;
        }
    
        public virtual System.DateTime ChangedWhen
        {
            get;
            set;
        }

        #endregion

    }
}
