//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BSERAWebService.Model.DataAccess
{
    public partial class S02002
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual Nullable<int> TransactionDataID
        {
            get { return _transactionDataID; }
            set
            {
                try
                {
                    _settingFK = true;
                    if (_transactionDataID != value)
                    {
                        if (TransactionData != null && TransactionData.ID != value)
                        {
                            TransactionData = null;
                        }
                        _transactionDataID = value;
                    }
                }
                finally
                {
                    _settingFK = false;
                }
            }
        }
        private Nullable<int> _transactionDataID;
    
        public virtual string PONumber
        {
            get;
            set;
        }
    
        public virtual Nullable<decimal> Version
        {
            get;
            set;
        }
    
        public virtual string StatusPOSERA
        {
            get;
            set;
        }
    
        public virtual string RejectRevisedPOSERA
        {
            get;
            set;
        }
    
        public virtual string DocumentNo
        {
            get;
            set;
        }
    
        public virtual string AIMaterialNumber
        {
            get;
            set;
        }
    
        public virtual string SERAMaterialNumber
        {
            get;
            set;
        }
    
        public virtual string SERAMaterialDescription
        {
            get;
            set;
        }
    
        public virtual string AIColor
        {
            get;
            set;
        }
    
        public virtual string SERAColor
        {
            get;
            set;
        }
    
        public virtual string QuotationNo
        {
            get;
            set;
        }
    
        public virtual string SalesOrderNo
        {
            get;
            set;
        }
    
        public virtual Nullable<double> DPPByVendor
        {
            get;
            set;
        }
    
        public virtual Nullable<double> PPNByVendor
        {
            get;
            set;
        }
    
        public virtual Nullable<double> BBNPriceByVendor
        {
            get;
            set;
        }
    
        public virtual string Currency
        {
            get;
            set;
        }
    
        public virtual string ChassisNumberByVendor
        {
            get;
            set;
        }
    
        public virtual string MachineNumberByVendor
        {
            get;
            set;
        }
    
        public virtual string CBUCKD
        {
            get;
            set;
        }
    
        public virtual Nullable<int> Year
        {
            get;
            set;
        }
    
        public virtual string FactureDONumber
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> BillingStatus
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> FactureDODate
        {
            get;
            set;
        }
    
        public virtual string NoFakturKendaraan
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TanggalFakturKendaraan
        {
            get;
            set;
        }
    
        public virtual string CancellationReason
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ActualDateDeliveryUnit
        {
            get;
            set;
        }
    
        public virtual string BSTKBNo
        {
            get;
            set;
        }
    
        public virtual string LicensePlateByVendor
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> STNKDateByVendor
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> RevisiSTNK
        {
            get;
            set;
        }
    
        public virtual string NoSertifikat
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TglSertifikat
        {
            get;
            set;
        }
    
        public virtual string NoFormulirA
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> TglFormulirA
        {
            get;
            set;
        }
    
        public virtual string NoSertifikatRegUjiTipe
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ActualDeliveryBPKBDate
        {
            get;
            set;
        }
    
        public virtual string NamaPenerima
        {
            get;
            set;
        }
    
        public virtual string AlamatPenerima
        {
            get;
            set;
        }
    
        public virtual string BPKBNumber
        {
            get;
            set;
        }
    
        public virtual string RemarksBPKB
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> RevisiBPKB
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual TransactionData TransactionData
        {
            get { return _transactionData; }
            set
            {
                if (!ReferenceEquals(_transactionData, value))
                {
                    var previousValue = _transactionData;
                    _transactionData = value;
                    FixupTransactionData(previousValue);
                }
            }
        }
        private TransactionData _transactionData;

        #endregion

        #region Association Fixup
    
        private bool _settingFK = false;
    
        private void FixupTransactionData(TransactionData previousValue)
        {
            if (previousValue != null && previousValue.S02002.Contains(this))
            {
                previousValue.S02002.Remove(this);
            }
    
            if (TransactionData != null)
            {
                if (!TransactionData.S02002.Contains(this))
                {
                    TransactionData.S02002.Add(this);
                }
                if (TransactionDataID != TransactionData.ID)
                {
                    TransactionDataID = TransactionData.ID;
                }
            }
            else if (!_settingFK)
            {
                TransactionDataID = null;
            }
        }

        #endregion

    }
}
