//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace B2BAISERA.Models.DataAccess
{
    public partial class B2BAISERAEntities : ObjectContext
    {
        public const string ConnectionString = "name=B2BAISERAEntities";
        public const string ContainerName = "B2BAISERAEntities";
    
        #region Constructors
    
        public B2BAISERAEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public B2BAISERAEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public B2BAISERAEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<DocumentFileType> DocumentFileTypes
        {
            get { return _documentFileTypes  ?? (_documentFileTypes = CreateObjectSet<DocumentFileType>("DocumentFileTypes")); }
        }
        private ObjectSet<DocumentFileType> _documentFileTypes;
    
        public ObjectSet<DocumentIPAddress> DocumentIPAddresses
        {
            get { return _documentIPAddresses  ?? (_documentIPAddresses = CreateObjectSet<DocumentIPAddress>("DocumentIPAddresses")); }
        }
        private ObjectSet<DocumentIPAddress> _documentIPAddresses;
    
        public ObjectSet<DocumentStatu> DocumentStatus
        {
            get { return _documentStatus  ?? (_documentStatus = CreateObjectSet<DocumentStatu>("DocumentStatus")); }
        }
        private ObjectSet<DocumentStatu> _documentStatus;
    
        public ObjectSet<Response> Responses
        {
            get { return _responses  ?? (_responses = CreateObjectSet<Response>("Responses")); }
        }
        private ObjectSet<Response> _responses;
    
        public ObjectSet<Transaction> Transactions
        {
            get { return _transactions  ?? (_transactions = CreateObjectSet<Transaction>("Transactions")); }
        }
        private ObjectSet<Transaction> _transactions;
    
        public ObjectSet<TransactionData> TransactionDatas
        {
            get { return _transactionDatas  ?? (_transactionDatas = CreateObjectSet<TransactionData>("TransactionDatas")); }
        }
        private ObjectSet<TransactionData> _transactionDatas;
    
        public ObjectSet<TransactionDataDetail> TransactionDataDetails
        {
            get { return _transactionDataDetails  ?? (_transactionDataDetails = CreateObjectSet<TransactionDataDetail>("TransactionDataDetails")); }
        }
        private ObjectSet<TransactionDataDetail> _transactionDataDetails;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;

        #endregion
        #region Function Imports
        public ObjectResult<string> sp_GetTest(string userName, string password)
        {
    
            ObjectParameter userNameParameter;
    
            if (userName != null)
            {
                userNameParameter = new ObjectParameter("userName", userName);
            }
            else
            {
                userNameParameter = new ObjectParameter("userName", typeof(string));
            }
    
            ObjectParameter passwordParameter;
    
            if (password != null)
            {
                passwordParameter = new ObjectParameter("password", password);
            }
            else
            {
                passwordParameter = new ObjectParameter("password", typeof(string));
            }
            return base.ExecuteFunction<string>("sp_GetTest", userNameParameter, passwordParameter);
        }

        #endregion
    }
}
