//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.DataAccess
{
    public partial class TransactionData
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int TransactionID
        {
            get { return _transactionID; }
            set
            {
                if (_transactionID != value)
                {
                    if (Transaction != null && Transaction.ID != value)
                    {
                        Transaction = null;
                    }
                    _transactionID = value;
                }
            }
        }
        private int _transactionID;
    
        public virtual string TransGUID
        {
            get;
            set;
        }
    
        public virtual string DocumentNumber
        {
            get;
            set;
        }
    
        public virtual string FileType
        {
            get;
            set;
        }
    
        public virtual string IPAddress
        {
            get;
            set;
        }
    
        public virtual string DestinationUser
        {
            get;
            set;
        }
    
        public virtual string Key1
        {
            get;
            set;
        }
    
        public virtual string Key2
        {
            get;
            set;
        }
    
        public virtual string Key3
        {
            get;
            set;
        }
    
        public virtual int DataLength
        {
            get;
            set;
        }
    
        public virtual string RowStatus
        {
            get;
            set;
        }
    
        public virtual string CreatedWho
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreatedWhen
        {
            get;
            set;
        }
    
        public virtual string ChangedWho
        {
            get;
            set;
        }
    
        public virtual System.DateTime ChangedWhen
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual Transaction Transaction
        {
            get { return _transaction; }
            set
            {
                if (!ReferenceEquals(_transaction, value))
                {
                    var previousValue = _transaction;
                    _transaction = value;
                    FixupTransaction(previousValue);
                }
            }
        }
        private Transaction _transaction;
    
        public virtual ICollection<TransactionDataDetail> TransactionDataDetails
        {
            get
            {
                if (_transactionDataDetails == null)
                {
                    var newCollection = new FixupCollection<TransactionDataDetail>();
                    newCollection.CollectionChanged += FixupTransactionDataDetails;
                    _transactionDataDetails = newCollection;
                }
                return _transactionDataDetails;
            }
            set
            {
                if (!ReferenceEquals(_transactionDataDetails, value))
                {
                    var previousValue = _transactionDataDetails as FixupCollection<TransactionDataDetail>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTransactionDataDetails;
                    }
                    _transactionDataDetails = value;
                    var newValue = value as FixupCollection<TransactionDataDetail>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTransactionDataDetails;
                    }
                }
            }
        }
        private ICollection<TransactionDataDetail> _transactionDataDetails;

        #endregion
        #region Association Fixup
    
        private void FixupTransaction(Transaction previousValue)
        {
            if (previousValue != null && previousValue.TransactionDatas.Contains(this))
            {
                previousValue.TransactionDatas.Remove(this);
            }
    
            if (Transaction != null)
            {
                if (!Transaction.TransactionDatas.Contains(this))
                {
                    Transaction.TransactionDatas.Add(this);
                }
                if (TransactionID != Transaction.ID)
                {
                    TransactionID = Transaction.ID;
                }
            }
        }
    
        private void FixupTransactionDataDetails(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (TransactionDataDetail item in e.NewItems)
                {
                    item.TransactionData = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TransactionDataDetail item in e.OldItems)
                {
                    if (ReferenceEquals(item.TransactionData, this))
                    {
                        item.TransactionData = null;
                    }
                }
            }
        }

        #endregion
    }
}
