//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2BAISERA.B2BAIWsDMZ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginRequest", Namespace="http://apps.astra.co.id/")]
    [System.SerializableAttribute()]
    public partial class LoginRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientTagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ClientTag {
            get {
                return this.ClientTagField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientTagField, value) != true)) {
                    this.ClientTagField = value;
                    this.RaisePropertyChanged("ClientTag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CommonResponse", Namespace="http://apps.astra.co.id/")]
    [System.SerializableAttribute()]
    public partial class CommonResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool AcknowledgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Acknowledge {
            get {
                return this.AcknowledgeField;
            }
            set {
                if ((this.AcknowledgeField.Equals(value) != true)) {
                    this.AcknowledgeField = value;
                    this.RaisePropertyChanged("Acknowledge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TicketNo {
            get {
                return this.TicketNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketNoField, value) != true)) {
                    this.TicketNoField = value;
                    this.RaisePropertyChanged("TicketNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UploadRequest", Namespace="http://apps.astra.co.id/")]
    [System.SerializableAttribute()]
    public partial class UploadRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private B2BAISERA.B2BAIWsDMZ.TransactionData[] transactionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TicketNo {
            get {
                return this.TicketNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketNoField, value) != true)) {
                    this.TicketNoField = value;
                    this.RaisePropertyChanged("TicketNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClientTag {
            get {
                return this.ClientTagField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientTagField, value) != true)) {
                    this.ClientTagField = value;
                    this.RaisePropertyChanged("ClientTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public B2BAISERA.B2BAIWsDMZ.TransactionData[] transactionData {
            get {
                return this.transactionDataField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionDataField, value) != true)) {
                    this.transactionDataField = value;
                    this.RaisePropertyChanged("transactionData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionData", Namespace="http://apps.astra.co.id/")]
    [System.SerializableAttribute()]
    public partial class TransactionData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Key1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Key2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Key3Field;
        
        private int DataLengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private B2BAISERA.B2BAIWsDMZ.ArrayOfString DataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransGUID {
            get {
                return this.TransGUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransGUIDField, value) != true)) {
                    this.TransGUIDField = value;
                    this.RaisePropertyChanged("TransGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DocumentNumber {
            get {
                return this.DocumentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNumberField, value) != true)) {
                    this.DocumentNumberField = value;
                    this.RaisePropertyChanged("DocumentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FileType {
            get {
                return this.FileTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FileTypeField, value) != true)) {
                    this.FileTypeField = value;
                    this.RaisePropertyChanged("FileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string DestinationUser {
            get {
                return this.DestinationUserField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationUserField, value) != true)) {
                    this.DestinationUserField = value;
                    this.RaisePropertyChanged("DestinationUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Key1 {
            get {
                return this.Key1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Key1Field, value) != true)) {
                    this.Key1Field = value;
                    this.RaisePropertyChanged("Key1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Key2 {
            get {
                return this.Key2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Key2Field, value) != true)) {
                    this.Key2Field = value;
                    this.RaisePropertyChanged("Key2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Key3 {
            get {
                return this.Key3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Key3Field, value) != true)) {
                    this.Key3Field = value;
                    this.RaisePropertyChanged("Key3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int DataLength {
            get {
                return this.DataLengthField;
            }
            set {
                if ((this.DataLengthField.Equals(value) != true)) {
                    this.DataLengthField = value;
                    this.RaisePropertyChanged("DataLength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public B2BAISERA.B2BAIWsDMZ.ArrayOfString Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://apps.astra.co.id/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadRequest", Namespace="http://apps.astra.co.id/")]
    [System.SerializableAttribute()]
    public partial class DownloadRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        private System.DateTime TransDateFromField;
        
        private System.DateTime TransDateToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Key1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Key2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Key3Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TicketNo {
            get {
                return this.TicketNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketNoField, value) != true)) {
                    this.TicketNoField = value;
                    this.RaisePropertyChanged("TicketNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClientTag {
            get {
                return this.ClientTagField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientTagField, value) != true)) {
                    this.ClientTagField = value;
                    this.RaisePropertyChanged("ClientTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FileType {
            get {
                return this.FileTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.FileTypeField, value) != true)) {
                    this.FileTypeField = value;
                    this.RaisePropertyChanged("FileType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SourceUser {
            get {
                return this.SourceUserField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceUserField, value) != true)) {
                    this.SourceUserField = value;
                    this.RaisePropertyChanged("SourceUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.DateTime TransDateFrom {
            get {
                return this.TransDateFromField;
            }
            set {
                if ((this.TransDateFromField.Equals(value) != true)) {
                    this.TransDateFromField = value;
                    this.RaisePropertyChanged("TransDateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime TransDateTo {
            get {
                return this.TransDateToField;
            }
            set {
                if ((this.TransDateToField.Equals(value) != true)) {
                    this.TransDateToField = value;
                    this.RaisePropertyChanged("TransDateTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Key1 {
            get {
                return this.Key1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Key1Field, value) != true)) {
                    this.Key1Field = value;
                    this.RaisePropertyChanged("Key1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Key2 {
            get {
                return this.Key2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Key2Field, value) != true)) {
                    this.Key2Field = value;
                    this.RaisePropertyChanged("Key2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string Key3 {
            get {
                return this.Key3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Key3Field, value) != true)) {
                    this.Key3Field = value;
                    this.RaisePropertyChanged("Key3");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DownloadResponse", Namespace="http://apps.astra.co.id/")]
    [System.SerializableAttribute()]
    public partial class DownloadResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool AcknowledgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private B2BAISERA.B2BAIWsDMZ.TransactionData[] transactionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Acknowledge {
            get {
                return this.AcknowledgeField;
            }
            set {
                if ((this.AcknowledgeField.Equals(value) != true)) {
                    this.AcknowledgeField = value;
                    this.RaisePropertyChanged("Acknowledge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TicketNo {
            get {
                return this.TicketNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketNoField, value) != true)) {
                    this.TicketNoField = value;
                    this.RaisePropertyChanged("TicketNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public B2BAISERA.B2BAIWsDMZ.TransactionData[] transactionData {
            get {
                return this.transactionDataField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionDataField, value) != true)) {
                    this.transactionDataField = value;
                    this.RaisePropertyChanged("transactionData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateStatusRequest", Namespace="http://apps.astra.co.id/")]
    [System.SerializableAttribute()]
    public partial class UpdateStatusRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TicketNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientTagField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private B2BAISERA.B2BAIWsDMZ.TransactionDataID[] transactionDataIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TicketNo {
            get {
                return this.TicketNoField;
            }
            set {
                if ((object.ReferenceEquals(this.TicketNoField, value) != true)) {
                    this.TicketNoField = value;
                    this.RaisePropertyChanged("TicketNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ClientTag {
            get {
                return this.ClientTagField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientTagField, value) != true)) {
                    this.ClientTagField = value;
                    this.RaisePropertyChanged("ClientTag");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public B2BAISERA.B2BAIWsDMZ.TransactionDataID[] transactionDataID {
            get {
                return this.transactionDataIDField;
            }
            set {
                if ((object.ReferenceEquals(this.transactionDataIDField, value) != true)) {
                    this.transactionDataIDField = value;
                    this.RaisePropertyChanged("transactionDataID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionDataID", Namespace="http://apps.astra.co.id/")]
    [System.SerializableAttribute()]
    public partial class TransactionDataID : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransGUIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Key1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Key2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Key3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TransGUID {
            get {
                return this.TransGUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TransGUIDField, value) != true)) {
                    this.TransGUIDField = value;
                    this.RaisePropertyChanged("TransGUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DocumentNumber {
            get {
                return this.DocumentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentNumberField, value) != true)) {
                    this.DocumentNumberField = value;
                    this.RaisePropertyChanged("DocumentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Key1 {
            get {
                return this.Key1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Key1Field, value) != true)) {
                    this.Key1Field = value;
                    this.RaisePropertyChanged("Key1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Key2 {
            get {
                return this.Key2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Key2Field, value) != true)) {
                    this.Key2Field = value;
                    this.RaisePropertyChanged("Key2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Key3 {
            get {
                return this.Key3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Key3Field, value) != true)) {
                    this.Key3Field = value;
                    this.RaisePropertyChanged("Key3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string TransStatus {
            get {
                return this.TransStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.TransStatusField, value) != true)) {
                    this.TransStatusField = value;
                    this.RaisePropertyChanged("TransStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LogMessage {
            get {
                return this.LogMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.LogMessageField, value) != true)) {
                    this.LogMessageField = value;
                    this.RaisePropertyChanged("LogMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://apps.astra.co.id/", ConfigurationName="B2BAIWsDMZ.B2BAIWebServiceDMZSoap")]
    public interface B2BAIWebServiceDMZSoap {
        
        // CODEGEN: Generating message contract since element name loginRequest from namespace http://apps.astra.co.id/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://apps.astra.co.id/LoginAuthentication", ReplyAction="*")]
        B2BAISERA.B2BAIWsDMZ.LoginAuthenticationResponse LoginAuthentication(B2BAISERA.B2BAIWsDMZ.LoginAuthenticationRequest request);
        
        // CODEGEN: Generating message contract since element name uploadRequest from namespace http://apps.astra.co.id/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://apps.astra.co.id/UploadDocument", ReplyAction="*")]
        B2BAISERA.B2BAIWsDMZ.UploadDocumentResponse UploadDocument(B2BAISERA.B2BAIWsDMZ.UploadDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name downloadRequest from namespace http://apps.astra.co.id/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://apps.astra.co.id/DownloadDocument", ReplyAction="*")]
        B2BAISERA.B2BAIWsDMZ.DownloadDocumentResponse DownloadDocument(B2BAISERA.B2BAIWsDMZ.DownloadDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name updateStatusRequest from namespace http://apps.astra.co.id/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://apps.astra.co.id/UpdateDocumentStatus", ReplyAction="*")]
        B2BAISERA.B2BAIWsDMZ.UpdateDocumentStatusResponse UpdateDocumentStatus(B2BAISERA.B2BAIWsDMZ.UpdateDocumentStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginAuthenticationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginAuthentication", Namespace="http://apps.astra.co.id/", Order=0)]
        public B2BAISERA.B2BAIWsDMZ.LoginAuthenticationRequestBody Body;
        
        public LoginAuthenticationRequest() {
        }
        
        public LoginAuthenticationRequest(B2BAISERA.B2BAIWsDMZ.LoginAuthenticationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class LoginAuthenticationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B2BAISERA.B2BAIWsDMZ.LoginRequest loginRequest;
        
        public LoginAuthenticationRequestBody() {
        }
        
        public LoginAuthenticationRequestBody(B2BAISERA.B2BAIWsDMZ.LoginRequest loginRequest) {
            this.loginRequest = loginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginAuthenticationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginAuthenticationResponse", Namespace="http://apps.astra.co.id/", Order=0)]
        public B2BAISERA.B2BAIWsDMZ.LoginAuthenticationResponseBody Body;
        
        public LoginAuthenticationResponse() {
        }
        
        public LoginAuthenticationResponse(B2BAISERA.B2BAIWsDMZ.LoginAuthenticationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class LoginAuthenticationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B2BAISERA.B2BAIWsDMZ.CommonResponse LoginAuthenticationResult;
        
        public LoginAuthenticationResponseBody() {
        }
        
        public LoginAuthenticationResponseBody(B2BAISERA.B2BAIWsDMZ.CommonResponse LoginAuthenticationResult) {
            this.LoginAuthenticationResult = LoginAuthenticationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDocument", Namespace="http://apps.astra.co.id/", Order=0)]
        public B2BAISERA.B2BAIWsDMZ.UploadDocumentRequestBody Body;
        
        public UploadDocumentRequest() {
        }
        
        public UploadDocumentRequest(B2BAISERA.B2BAIWsDMZ.UploadDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class UploadDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B2BAISERA.B2BAIWsDMZ.UploadRequest uploadRequest;
        
        public UploadDocumentRequestBody() {
        }
        
        public UploadDocumentRequestBody(B2BAISERA.B2BAIWsDMZ.UploadRequest uploadRequest) {
            this.uploadRequest = uploadRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadDocumentResponse", Namespace="http://apps.astra.co.id/", Order=0)]
        public B2BAISERA.B2BAIWsDMZ.UploadDocumentResponseBody Body;
        
        public UploadDocumentResponse() {
        }
        
        public UploadDocumentResponse(B2BAISERA.B2BAIWsDMZ.UploadDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class UploadDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B2BAISERA.B2BAIWsDMZ.CommonResponse UploadDocumentResult;
        
        public UploadDocumentResponseBody() {
        }
        
        public UploadDocumentResponseBody(B2BAISERA.B2BAIWsDMZ.CommonResponse UploadDocumentResult) {
            this.UploadDocumentResult = UploadDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadDocument", Namespace="http://apps.astra.co.id/", Order=0)]
        public B2BAISERA.B2BAIWsDMZ.DownloadDocumentRequestBody Body;
        
        public DownloadDocumentRequest() {
        }
        
        public DownloadDocumentRequest(B2BAISERA.B2BAIWsDMZ.DownloadDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class DownloadDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B2BAISERA.B2BAIWsDMZ.DownloadRequest downloadRequest;
        
        public DownloadDocumentRequestBody() {
        }
        
        public DownloadDocumentRequestBody(B2BAISERA.B2BAIWsDMZ.DownloadRequest downloadRequest) {
            this.downloadRequest = downloadRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DownloadDocumentResponse", Namespace="http://apps.astra.co.id/", Order=0)]
        public B2BAISERA.B2BAIWsDMZ.DownloadDocumentResponseBody Body;
        
        public DownloadDocumentResponse() {
        }
        
        public DownloadDocumentResponse(B2BAISERA.B2BAIWsDMZ.DownloadDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class DownloadDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B2BAISERA.B2BAIWsDMZ.DownloadResponse DownloadDocumentResult;
        
        public DownloadDocumentResponseBody() {
        }
        
        public DownloadDocumentResponseBody(B2BAISERA.B2BAIWsDMZ.DownloadResponse DownloadDocumentResult) {
            this.DownloadDocumentResult = DownloadDocumentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDocumentStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDocumentStatus", Namespace="http://apps.astra.co.id/", Order=0)]
        public B2BAISERA.B2BAIWsDMZ.UpdateDocumentStatusRequestBody Body;
        
        public UpdateDocumentStatusRequest() {
        }
        
        public UpdateDocumentStatusRequest(B2BAISERA.B2BAIWsDMZ.UpdateDocumentStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class UpdateDocumentStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B2BAISERA.B2BAIWsDMZ.UpdateStatusRequest updateStatusRequest;
        
        public UpdateDocumentStatusRequestBody() {
        }
        
        public UpdateDocumentStatusRequestBody(B2BAISERA.B2BAIWsDMZ.UpdateStatusRequest updateStatusRequest) {
            this.updateStatusRequest = updateStatusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDocumentStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDocumentStatusResponse", Namespace="http://apps.astra.co.id/", Order=0)]
        public B2BAISERA.B2BAIWsDMZ.UpdateDocumentStatusResponseBody Body;
        
        public UpdateDocumentStatusResponse() {
        }
        
        public UpdateDocumentStatusResponse(B2BAISERA.B2BAIWsDMZ.UpdateDocumentStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://apps.astra.co.id/")]
    public partial class UpdateDocumentStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public B2BAISERA.B2BAIWsDMZ.CommonResponse UpdateDocumentStatusResult;
        
        public UpdateDocumentStatusResponseBody() {
        }
        
        public UpdateDocumentStatusResponseBody(B2BAISERA.B2BAIWsDMZ.CommonResponse UpdateDocumentStatusResult) {
            this.UpdateDocumentStatusResult = UpdateDocumentStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface B2BAIWebServiceDMZSoapChannel : B2BAISERA.B2BAIWsDMZ.B2BAIWebServiceDMZSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class B2BAIWebServiceDMZSoapClient : System.ServiceModel.ClientBase<B2BAISERA.B2BAIWsDMZ.B2BAIWebServiceDMZSoap>, B2BAISERA.B2BAIWsDMZ.B2BAIWebServiceDMZSoap {
        
        public B2BAIWebServiceDMZSoapClient() {
        }
        
        public B2BAIWebServiceDMZSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public B2BAIWebServiceDMZSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B2BAIWebServiceDMZSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B2BAIWebServiceDMZSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2BAISERA.B2BAIWsDMZ.LoginAuthenticationResponse B2BAISERA.B2BAIWsDMZ.B2BAIWebServiceDMZSoap.LoginAuthentication(B2BAISERA.B2BAIWsDMZ.LoginAuthenticationRequest request) {
            return base.Channel.LoginAuthentication(request);
        }
        
        public B2BAISERA.B2BAIWsDMZ.CommonResponse LoginAuthentication(B2BAISERA.B2BAIWsDMZ.LoginRequest loginRequest) {
            B2BAISERA.B2BAIWsDMZ.LoginAuthenticationRequest inValue = new B2BAISERA.B2BAIWsDMZ.LoginAuthenticationRequest();
            inValue.Body = new B2BAISERA.B2BAIWsDMZ.LoginAuthenticationRequestBody();
            inValue.Body.loginRequest = loginRequest;
            B2BAISERA.B2BAIWsDMZ.LoginAuthenticationResponse retVal = ((B2BAISERA.B2BAIWsDMZ.B2BAIWebServiceDMZSoap)(this)).LoginAuthentication(inValue);
            return retVal.Body.LoginAuthenticationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2BAISERA.B2BAIWsDMZ.UploadDocumentResponse B2BAISERA.B2BAIWsDMZ.B2BAIWebServiceDMZSoap.UploadDocument(B2BAISERA.B2BAIWsDMZ.UploadDocumentRequest request) {
            return base.Channel.UploadDocument(request);
        }
        
        public B2BAISERA.B2BAIWsDMZ.CommonResponse UploadDocument(B2BAISERA.B2BAIWsDMZ.UploadRequest uploadRequest) {
            B2BAISERA.B2BAIWsDMZ.UploadDocumentRequest inValue = new B2BAISERA.B2BAIWsDMZ.UploadDocumentRequest();
            inValue.Body = new B2BAISERA.B2BAIWsDMZ.UploadDocumentRequestBody();
            inValue.Body.uploadRequest = uploadRequest;
            B2BAISERA.B2BAIWsDMZ.UploadDocumentResponse retVal = ((B2BAISERA.B2BAIWsDMZ.B2BAIWebServiceDMZSoap)(this)).UploadDocument(inValue);
            return retVal.Body.UploadDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2BAISERA.B2BAIWsDMZ.DownloadDocumentResponse B2BAISERA.B2BAIWsDMZ.B2BAIWebServiceDMZSoap.DownloadDocument(B2BAISERA.B2BAIWsDMZ.DownloadDocumentRequest request) {
            return base.Channel.DownloadDocument(request);
        }
        
        public B2BAISERA.B2BAIWsDMZ.DownloadResponse DownloadDocument(B2BAISERA.B2BAIWsDMZ.DownloadRequest downloadRequest) {
            B2BAISERA.B2BAIWsDMZ.DownloadDocumentRequest inValue = new B2BAISERA.B2BAIWsDMZ.DownloadDocumentRequest();
            inValue.Body = new B2BAISERA.B2BAIWsDMZ.DownloadDocumentRequestBody();
            inValue.Body.downloadRequest = downloadRequest;
            B2BAISERA.B2BAIWsDMZ.DownloadDocumentResponse retVal = ((B2BAISERA.B2BAIWsDMZ.B2BAIWebServiceDMZSoap)(this)).DownloadDocument(inValue);
            return retVal.Body.DownloadDocumentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        B2BAISERA.B2BAIWsDMZ.UpdateDocumentStatusResponse B2BAISERA.B2BAIWsDMZ.B2BAIWebServiceDMZSoap.UpdateDocumentStatus(B2BAISERA.B2BAIWsDMZ.UpdateDocumentStatusRequest request) {
            return base.Channel.UpdateDocumentStatus(request);
        }
        
        public B2BAISERA.B2BAIWsDMZ.CommonResponse UpdateDocumentStatus(B2BAISERA.B2BAIWsDMZ.UpdateStatusRequest updateStatusRequest) {
            B2BAISERA.B2BAIWsDMZ.UpdateDocumentStatusRequest inValue = new B2BAISERA.B2BAIWsDMZ.UpdateDocumentStatusRequest();
            inValue.Body = new B2BAISERA.B2BAIWsDMZ.UpdateDocumentStatusRequestBody();
            inValue.Body.updateStatusRequest = updateStatusRequest;
            B2BAISERA.B2BAIWsDMZ.UpdateDocumentStatusResponse retVal = ((B2BAISERA.B2BAIWsDMZ.B2BAIWebServiceDMZSoap)(this)).UpdateDocumentStatus(inValue);
            return retVal.Body.UpdateDocumentStatusResult;
        }
    }
}
