//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOM_TRANSACTIONDATADETAIL
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual int TransactionDataID
        {
            get { return _transactionDataID; }
            set
            {
                if (_transactionDataID != value)
                {
                    if (CUSTOM_TRANSACTIONDATA != null && CUSTOM_TRANSACTIONDATA.ID != value)
                    {
                        CUSTOM_TRANSACTIONDATA = null;
                    }
                    _transactionDataID = value;
                }
            }
        }
        private int _transactionDataID;
    
        public virtual string Data
        {
            get;
            set;
        }
    
        public virtual string dibuatOleh
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> dibuatTanggal
        {
            get;
            set;
        }
    
        public virtual string diubahOleh
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> diubahTanggal
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual CUSTOM_TRANSACTIONDATA CUSTOM_TRANSACTIONDATA
        {
            get { return _cUSTOM_TRANSACTIONDATA; }
            set
            {
                if (!ReferenceEquals(_cUSTOM_TRANSACTIONDATA, value))
                {
                    var previousValue = _cUSTOM_TRANSACTIONDATA;
                    _cUSTOM_TRANSACTIONDATA = value;
                    FixupCUSTOM_TRANSACTIONDATA(previousValue);
                }
            }
        }
        private CUSTOM_TRANSACTIONDATA _cUSTOM_TRANSACTIONDATA;

        #endregion

        #region Association Fixup
    
        private void FixupCUSTOM_TRANSACTIONDATA(CUSTOM_TRANSACTIONDATA previousValue)
        {
            if (previousValue != null && previousValue.CUSTOM_TRANSACTIONDATADETAIL.Contains(this))
            {
                previousValue.CUSTOM_TRANSACTIONDATADETAIL.Remove(this);
            }
    
            if (CUSTOM_TRANSACTIONDATA != null)
            {
                if (!CUSTOM_TRANSACTIONDATA.CUSTOM_TRANSACTIONDATADETAIL.Contains(this))
                {
                    CUSTOM_TRANSACTIONDATA.CUSTOM_TRANSACTIONDATADETAIL.Add(this);
                }
                if (TransactionDataID != CUSTOM_TRANSACTIONDATA.ID)
                {
                    TransactionDataID = CUSTOM_TRANSACTIONDATA.ID;
                }
            }
        }

        #endregion

    }
}
