//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace B2BAISERA.Models.EFServer
{
    public partial class CUSTOM_TRANSACTION
    {
        #region Primitive Properties
    
        public virtual int ID
        {
            get;
            set;
        }
    
        public virtual string TicketNo
        {
            get;
            set;
        }
    
        public virtual string ClientTag
        {
            get;
            set;
        }
    
        public virtual string CreatedWho
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> CreatedWhen
        {
            get;
            set;
        }
    
        public virtual string ChangedWho
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> ChangedWhen
        {
            get;
            set;
        }
    
        public virtual Nullable<bool> Acknowledge
        {
            get;
            set;
        }
    
        public virtual string Message
        {
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
        public virtual ICollection<CUSTOM_TRANSACTIONDATA> CUSTOM_TRANSACTIONDATA
        {
            get
            {
                if (_cUSTOM_TRANSACTIONDATA == null)
                {
                    var newCollection = new FixupCollection<CUSTOM_TRANSACTIONDATA>();
                    newCollection.CollectionChanged += FixupCUSTOM_TRANSACTIONDATA;
                    _cUSTOM_TRANSACTIONDATA = newCollection;
                }
                return _cUSTOM_TRANSACTIONDATA;
            }
            set
            {
                if (!ReferenceEquals(_cUSTOM_TRANSACTIONDATA, value))
                {
                    var previousValue = _cUSTOM_TRANSACTIONDATA as FixupCollection<CUSTOM_TRANSACTIONDATA>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupCUSTOM_TRANSACTIONDATA;
                    }
                    _cUSTOM_TRANSACTIONDATA = value;
                    var newValue = value as FixupCollection<CUSTOM_TRANSACTIONDATA>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupCUSTOM_TRANSACTIONDATA;
                    }
                }
            }
        }
        private ICollection<CUSTOM_TRANSACTIONDATA> _cUSTOM_TRANSACTIONDATA;

        #endregion

        #region Association Fixup
    
        private void FixupCUSTOM_TRANSACTIONDATA(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (CUSTOM_TRANSACTIONDATA item in e.NewItems)
                {
                    item.CUSTOM_TRANSACTION = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (CUSTOM_TRANSACTIONDATA item in e.OldItems)
                {
                    if (ReferenceEquals(item.CUSTOM_TRANSACTION, this))
                    {
                        item.CUSTOM_TRANSACTION = null;
                    }
                }
            }
        }

        #endregion

    }
}
