//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace B2BAISERA.Models.EFServer
{
    public partial class EProcEntities : ObjectContext
    {
        public const string ConnectionString = "name=EProcEntities";
        public const string ContainerName = "EProcEntities";
    
        #region Constructors
    
        public EProcEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EProcEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public EProcEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<CUSTOM_TRANSACTION> CUSTOM_TRANSACTION
        {
            get { return _cUSTOM_TRANSACTION  ?? (_cUSTOM_TRANSACTION = CreateObjectSet<CUSTOM_TRANSACTION>("CUSTOM_TRANSACTION")); }
        }
        private ObjectSet<CUSTOM_TRANSACTION> _cUSTOM_TRANSACTION;
    
        public ObjectSet<CUSTOM_TRANSACTIONDATA> CUSTOM_TRANSACTIONDATA
        {
            get { return _cUSTOM_TRANSACTIONDATA  ?? (_cUSTOM_TRANSACTIONDATA = CreateObjectSet<CUSTOM_TRANSACTIONDATA>("CUSTOM_TRANSACTIONDATA")); }
        }
        private ObjectSet<CUSTOM_TRANSACTIONDATA> _cUSTOM_TRANSACTIONDATA;
    
        public ObjectSet<CUSTOM_TRANSACTIONDATADETAIL> CUSTOM_TRANSACTIONDATADETAIL
        {
            get { return _cUSTOM_TRANSACTIONDATADETAIL  ?? (_cUSTOM_TRANSACTIONDATADETAIL = CreateObjectSet<CUSTOM_TRANSACTIONDATADETAIL>("CUSTOM_TRANSACTIONDATADETAIL")); }
        }
        private ObjectSet<CUSTOM_TRANSACTIONDATADETAIL> _cUSTOM_TRANSACTIONDATADETAIL;
    
        public ObjectSet<CUSTOM_USER> CUSTOM_USER
        {
            get { return _cUSTOM_USER  ?? (_cUSTOM_USER = CreateObjectSet<CUSTOM_USER>("CUSTOM_USER")); }
        }
        private ObjectSet<CUSTOM_USER> _cUSTOM_USER;
    
        public ObjectSet<CUSTOM_LOG> CUSTOM_LOG
        {
            get { return _cUSTOM_LOG  ?? (_cUSTOM_LOG = CreateObjectSet<CUSTOM_LOG>("CUSTOM_LOG")); }
        }
        private ObjectSet<CUSTOM_LOG> _cUSTOM_LOG;
    
        public ObjectSet<CUSTOM_S02009_HS> CUSTOM_S02009_HS
        {
            get { return _cUSTOM_S02009_HS  ?? (_cUSTOM_S02009_HS = CreateObjectSet<CUSTOM_S02009_HS>("CUSTOM_S02009_HS")); }
        }
        private ObjectSet<CUSTOM_S02009_HS> _cUSTOM_S02009_HS;
    
        public ObjectSet<CUSTOM_S02009_IS> CUSTOM_S02009_IS
        {
            get { return _cUSTOM_S02009_IS  ?? (_cUSTOM_S02009_IS = CreateObjectSet<CUSTOM_S02009_IS>("CUSTOM_S02009_IS")); }
        }
        private ObjectSet<CUSTOM_S02009_IS> _cUSTOM_S02009_IS;
    
        public ObjectSet<CUSTOM_S02009_TEMP_HS> CUSTOM_S02009_TEMP_HS
        {
            get { return _cUSTOM_S02009_TEMP_HS  ?? (_cUSTOM_S02009_TEMP_HS = CreateObjectSet<CUSTOM_S02009_TEMP_HS>("CUSTOM_S02009_TEMP_HS")); }
        }
        private ObjectSet<CUSTOM_S02009_TEMP_HS> _cUSTOM_S02009_TEMP_HS;
    
        public ObjectSet<CUSTOM_S02009_TEMP_IS> CUSTOM_S02009_TEMP_IS
        {
            get { return _cUSTOM_S02009_TEMP_IS  ?? (_cUSTOM_S02009_TEMP_IS = CreateObjectSet<CUSTOM_S02009_TEMP_IS>("CUSTOM_S02009_TEMP_IS")); }
        }
        private ObjectSet<CUSTOM_S02009_TEMP_IS> _cUSTOM_S02009_TEMP_IS;

        #endregion

        #region Function Imports
        public ObjectResult<CUSTOM_S02009_TEMP_HS> sp_CreatePOSeraS02009ToAI_HS()
        {
            return base.ExecuteFunction<CUSTOM_S02009_TEMP_HS>("sp_CreatePOSeraS02009ToAI_HS");
        }
        public ObjectResult<CUSTOM_S02009_TEMP_IS> sp_CreatePOSeras02009ToAI_IS()
        {
            return base.ExecuteFunction<CUSTOM_S02009_TEMP_IS>("sp_CreatePOSeras02009ToAI_IS");
        }

        #endregion

    }
}
